### Denite {{{
# Asynchronous unite all interfaces
[[plugins]]
repo = 'Shougo/denite.nvim'
depends = ['unite-outline', 'neomru.vim', 'neoyank.vim']
on_cmd = 'Denite'
hook_add = '''
source ~/.config/nvim/plugins/denite.nvim.rc.vim
'''
hook_post_source = '''
source ~/.config/nvim/plugins/denite_post.nvim.rc.vim
'''

[[plugins]]
repo = 'Shougo/unite-outline'

[[plugins]]
repo = 'Shougo/neomru.vim'

[[plugins]]
repo = 'Shougo/neoyank.vim'
### }}}

### Defx {{{
# File explorer
[[plugins]]
repo = 'Shougo/defx.nvim'
on_cmd = 'Defx'
depends = ['defx-icons', 'defx-git']
hook_done_update = '''
source ~/.config/nvim/plugins/defx.nvim.rc.vim
'''

[[plugins]]
repo ='kristijanhusak/defx-icons'

[[plugins]]
repo ='kristijanhusak/defx-git'
### }}}


### Deoplete {{{
#[[plugins]]
#repo = 'Shougo/deoplete.nvim'
#depends = ['context_filetype.vim','neosnippet']
#on_event = 'InsertEnter'
#if = 'has("python3")'
#in_i = 1
#hook_source = '''
#source ~/.config/nvim/plugins/deoplete.rc.vim
#'''

[[plugins]]
repo = 'Shougo/neosnippet'
on_event = 'InsertCharPre'
on_i = 1
on_ft = ['snippet']
depends = ['context_filetype.vim','neosnippet-snippets']
hook_source = '''
source ~/.config/nvim/plugins/neosnippet.rc.vim
'''

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'Shougo/context_filetype.vim'
###}}}

## Latex
[[plugins]]
repo = 'lervag/vimtex'
hook_add = '''
source ~/.config/nvim/plugins/vimtex.rc.vim
'''

## syntax {{{
[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'
