#!/bin/zsh

## Separator symbols
SEPARATOR_LEFT="\ue0b0"
SEPARATOR_RIGHT="\ue0b2 "
SUBSEPARATOR_LEFT="\ue0b1 "
SUBSEPARATOR_RIGHT="\ue0b3 "

## Git symbols
GIT_SYMBOL="\uf7a1"
UNSTAGE="\uf067"
STAGE="\uf12a"
COMMIT="\ue73b"
ALLOK="\uf00c"

if git_status=$(cd $1 && git status 2>/dev/null ); then
  git_branch="$(echo $git_status | awk 'NR==1 {print $3}')"
  case "$git_status" in
    "*Changes\ not\ staged*" )
      stage_symbol=${UNSTAGE} ;;
    "*Changes\ to\ be\ committed*" )
      stage_symbol=${STAGE} ;;
    "*\(uses*" )
      stage_symbol=${COMMIT} ;;
    "*"" )
      stage_symbol=${ALLOK} ;;
  esac
  case $git_branch in
    master | main )
      git_info="#[bg=colour148]${SEPARATOR_LEFT}#[bg=colour148,fg=colour022] ${git_branch} ${stage_symbol} #[bg=default,fg=colour148]${SEPARATOR_LEFT}" ;;
    develop )
      git_info="#[bg=colour024]${SEPARATOR_LEFT}#[bg=colour024,fg=colour117] ${git_branch} ${stage_symbol} #[bg=default,fg=colour024]${SEPARATOR_LEFT}" ;;
    *feature* )
      git_info="#[bg=colour208]${SEPARATOR_LEFT}#[bg=colour208,fg=colour088] ${git_branch} ${stage_symbol} #[bg=default,fg=colour208]${SEPARATOR_LEFT}" ;;
    release )
      git_info="#[bg=colour055]${SEPARATOR_LEFT}#[bg=colour055,fg=colour189] ${git_branch} ${stage_symbol} #[bg=default,fg=colour055]${SEPARATOR_LEFT}" ;;
    *hotfix* )
      git_info="#[bg=colour196]${SEPARATOR_LEFT}#[bg=colour196,fg=colour250] ${git_branch} ${stage_symbol} #[bg=default,fg=colour196]${SEPARATOR_LEFT}" ;;
    * )
      git_info="#[bg=colour252]${SEPARATOR_LEFT}#[bg=colour252,fg=colour241] ${git_branch} ${stage_symbol} #[bg=default,fg=colour252]${SEPARATOR_LEFT}" ;;
  esac
else
  git_info="#[bg=default]${SEPARATOR_LEFT}"
fi

if [[ $3 = "ssh" ]]; then
  pane_pid=$4
  info=$({ pgrep -flaP $pane_pid ; ps -o command -p $pane_pid; } \
    | xargs -I{} echo {} \
    | awk '/ssh/' \
    | sed -E 's/^[0-9]*[[:blank:]]*ssh //' \
  )
  port=$(echo $info | grep -Eo '\-p ([0-9]+)'|sed 's/-p //')
  if [ -z $port ]; then
    local port=22
  fi
  info=$(echo $info | sed 's/\-p '"$port"'//g')
  user=$(echo $info | awk '{print $NF}' | cut -f1 -d@)
  host=$(echo $info | awk '{print $NF}' | cut -f2 -d@)

  if [ $user = $host ]; then
    user=$(whoami)
    list=$(awk '
      $1 == "HostName" {
        gsub("\\\\.", "\\\\.", $2);
        gsub("\\\\*", ".*", $2);
        host = $2;
        next;
      }
      $1 == "User" {
      $1 = "";
        sub( /^[[:space:]]*/, "" );
        printf "%s|%s\n", host, $0;
      }' ~/.ssh/config
    )
    echo $list | while read line; do
      host_user=${line#*|}
      if [[ "$host" =~ $line ]]; then
        user=$host_user
        break
      fi
    done
  fi
  #ssh_hostname=" ssh:$user@$host "
else
  user=$(whoami)
  host=$(hostname -s)
fi
username="$user"
hostname="$host"

if [ "$2" -eq "1" ]; then
  echo "#[fg=colour22,bg=colour148,bold] ${username}@${hostname} #[fg=colour148,bg=colour240]${SEPARATOR_LEFT}#[fg=colour231,bg=colour240,bold] $1 #[fg=colour240]${git_info})#[default]"
  #echo "#[fg=colour22,bg=colour148,bold] ${info}@${hostname} #[fg=colour148,bg=colour240]${SEPARATOR_LEFT}#[fg=colour231,bg=colour240,bold] $1 #[fg=colour240]${git_info})#[default]"
else
  echo "#[fg=colour235,bg=colour241,bold] ${username}@${hostname} #[fg=colour241,bg=colour235]${SEPARATOR_LEFT}#[fg=colour240,bg=colour235,bold] $1 #[fg=colour235]#[bg=default]${SEPARATOR_LEFT}"
fi

