[tools]
python     = "3.12.13"
uv         = "0.12.1"
# ruby       = "3.4"
node       = "22.22.2"
java       = "21.0.2"
rust       = "1.95.0"
# go         = "1.26.5"
lua        = "5.5.0"
jq         = "1.8.1"
peco       = "0.6.0"
fzf        = "0.72.0"
# ghq        = "1.10.1"
github-cli = "2.91.0"
vim        = "9.2.0398"
neovim     = "0.12.2"
tmux       = "3.6a"
"cargo:herdr" = "0.1.0"
"npm:hunkdiff" = "0.17.7"
"npm:git-cz" = "4.9.0"
