[tools]
python = "3.12.14"
uv = "0.12.5"
node = "24.19.0"
java = "openjdk-21"
rust = "1.97.1"
lua = { version = "5.1", os = ["linux"] }
jq = "1.8.2"
fzf = "0.73.1"
neovim = "0.12.5"
shellcheck = "0.11.0"
shfmt = "3.13.1"
stylua = "2.5.2"
taplo = "0.10.0"
actionlint = "1.7.12"
ruff = "0.16.4"
herdr = "0.8.2"
hunkdiff = { version = "0.19.0", rename_exe = "hunkdiff" }
tree-sitter-cli = { version = "0.26.13", os = ["linux"] }
starship = { version = "v1.26.0", os = ["linux"] }
git-cz = "4.9.0"
prettier = "3.9.6"

[tool_alias]
herdr = "github:herdrdev/herdr"
hunkdiff = "github:modem-dev/hunk"
ruff = "pipx:ruff"
tree-sitter-cli = "cargo:tree-sitter-cli"
starship = "cargo:starship"
git-cz = "npm:git-cz"
prettier = "npm:prettier"

