name: linux

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  ubuntu-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Installation
        run: make install
      - name: Install anyenv
        run: bash ./bin/install_anyenv1.sh


