name: linux

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  ubuntu-test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        script: ["./bin/install_anyenv1.sh"]

    steps:
      - uses: actions/checkout@v2
      - name: Show GitHub Workspace
        working-directory: ./$GITHUB_WORKSPACE
        run: echo '$GITHUB_WORKSPACE'
      - name: Clone repository
        run: git clone --verbose --progress https://github.com/k5-mot/dotfiles.git $HOME
      - name: Install configurations
        run: make install
      - name: Install packages via apt
        working-directory: ${GITHUB_WORKSPACE}/bin
        run: sudo bash ./install_apt_packages.sh
      - name: Install anyenv
        run: ${{matrix.script}}


