name: linux

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ubuntu-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install zsh.
        run: |
          sudo apt install zsh -y

      - name: Install configurations
        shell: bash
        run: make install

      - name: Update & Install packages via apt
        shell: bash
        run: |
          cd ${GITHUB_WORKSPACE}/scripts/apt
          # ./update.sh
          # ./install.sh

      - name: Check $PATH.
        shell: bash
        run: |
          export PATH=$HOME/.local/usr/bin:$PATH
          echo ${GITHUB_WORKSPACE}
          echo "PATH : "
          echo $PATH | sed -e "s/:/\n/g"

      - name: Install rust.
        shell: zsh {0}
        run: |
          cd $GITHUB_WORKSPACE/config/.config/scripts/rust
          ./install.sh

      - name: Install rust packages via cargo.
        shell: zsh {0}
        run: |
          cd $GITHUB_WORKSPACE/config/.config/scripts/rust
          ./cargo.sh

      - name: Install alacritty.
        shell: zsh {0}
        run: |
          cd $GITHUB_WORKSPACE/config/.config/scripts/rust
          #./alacritty.sh

      - name: Install porg.
        shell: zsh {0}
        run: |
          cd $GITHUB_WORKSPACE/config/.config/scripts/porg
          ./porg.sh

      - name: Install Git via porg.
        shell: zsh {0}
        run: |
          cd $GITHUB_WORKSPACE/config/.config/scripts/porg
          ./git.sh

      - name: Install Xsel via porg.
        shell: zsh {0}
        run: |
          cd $GITHUB_WORKSPACE/config/.config/scripts/porg
          ./xsel.sh

      - name: Install Tmux via porg.
        shell: zsh {0}
        run: |
          cd $GITHUB_WORKSPACE/config/.config/scripts/porg
          ./libevent.sh
          ./ncurses.sh
          ./tmux.sh

      - name: Install Vim via porg.
        shell: zsh {0}
        run: |
          cd $GITHUB_WORKSPACE/config/.config/scripts/porg
          ./vim.sh

      - name: Install Neovim via porg.
        shell: zsh {0}
        run: |
          cd $GITHUB_WORKSPACE/config/.config/scripts/porg
          ./neovim.sh

