name: linux

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ubuntu-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install configurations
        shell: bash
        run: make install

      - name: Update & Install packages via apt
        shell: bash
        run: |
          cd ${GITHUB_WORKSPACE}/scripts/apt
          # ./update.sh
          # ./install.sh

      - name: Check $PATH.
        shell: bash
        run: |
          export PATH=$HOME/.local/usr/bin:$PATH
          echo ${GITHUB_WORKSPACE}
          echo "PATH : "
          echo $PATH | sed -e "s/:/\n/g"

      - name: Install rust.
        shell: bash
        run: |
          cd ${GITHUB_WORKSPACE}/scripts/rust
          ./install.sh

          #- name: Install rust packages via cargo.
          #  shell: bash
          #  run: |
          #    cd ${GITHUB_WORKSPACE}/scripts/rust
          #    ./cargo.sh

          #- name: Install alacritty.
          #  shell: bash
          #  run: |
          #    cd ${GITHUB_WORKSPACE}/scripts/rust
          #    ./alacritty.sh

      - name: Install packages via porg.
        shell: bash
        run: |
          cd ${GITHUB_WORKSPACE}/scripts/porg
          ./install-full.sh

